name: Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [0.10.0]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup spacectl
      uses: ./
      with:
        version: ${{ matrix.version }}

    - name: Capture spacectl version installed
      run: |
        export SPACECTL_VERSION=$( spacectl --version )
        echo 'SPACECTL_VERSION_INSTALLED<<EOF' >> $SPACECTL_ENV
        spacectl --version >> $SPACECTL_ENV
        echo 'EOF' >> $SPACECTL_ENV
    - name: Verify
      shell: python
      env:
        SPACECTL_VERSION_EXPECTED: ${{ matrix.version }}
      run: |
        import sys, os
        sys.exit(
            int(not os.environ["SPACECTL_VERSION_EXPECTED"] in os.environ["SPACECTL_VERSION_INSTALLED"])
        )
