name: Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [0.10.0]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup spacectl
      uses: ./
      with:
        version: ${{ matrix.version }}

    - name: Capture spacectl version installed
      run: |
        spacetl --version | grep ${{ matrix['version']}}

